import 'package:get/get.dart';

class Language implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "gallery": "Gallery",
          "camera": "Camera",
          "chooseImage": "Choose Your Image ",
          "logo": "Logo",
          "login": "Login",
          "signUp": "Sign Up",
          "theSignUp": "Sign Up",
          "continue": "Continue",
          "filter": "Filter",
          "bestSellers": "Best Sellers",
          "mostGifted": "Most Gifted",
          "offers": "Offers",
          "username": "User Name",
          "password": "Password",
          "repassword": "RePassword",
          "address": "Address",
          "email": "Email",
          "phoneNumber": "Phone Number",
          "cart": "My Cart",
          "forgetPassword": "Forget Password?",
          "noAccount": "Don't have an account?",
          "done": "Done",
          "settings": "Settings",
          "accountInformation": "Account Information",
          "paymentMethods": "Payment Methods",
          "paymentMethod": "Payment Method",
          "orderHistory": "Order History",
          "order": " Order: ",
          "securitySettings": "Security Settings",
          "suuport&feedback": "Support & Feedback",
          "languageSettings": "Language Settings",
          "legalInformation": "Legal Information",
          "themes": "Themes",
          "aboutUs": "About Us",
          "logOut": "Logout",
          "logOutmessage": "Are You Sure You Want To Logout?",
          "yes": "Yes",
          "no": "No",
          "tryAgain": "Try Again",
          "ok": "Ok",
          "helloUser": "Hello User",
          "customizeSpecialGifts": "Customize Special Gifts",
          "plusOne": "+1",
          "gifts": " Gifts",
          "search": "Search",
          "flowers": "Flowers",
          "plants": "Plants",
          "bouquet": "Bouquet",
          "profilePhoto": "Add Profile Photo",
          "uploadPdf": "Upload Pdf",
          "hasAccount": "Already have an account?",
          "verficationCode": "Verification Code",
          "enterCodeMessage":
              "Please enter verification code sent to Email address .....@Gmail.com ",
          "10minsValid": "Valid to 10 minutes",
          "reSendCode": "Re Send Code",
          "verificationCodeContent":
              "Verification code consists of numbers and letters ",
          "submit": "Submit",
          "price": "Price: ",
          "catOfFlowers": "Category Of Flowers",
          "addToCart": "Add To Cart",
          "color": "Color",
          "flowerInfo": "Flower Information",
          "takeCareOfPlant": "How To Take Care Of It",
          "addToBasket": "Add To Basket",
          "buyNow": "Buy Now",
          "reviews": "Reviews",
          "dateOfReview": "Date Of Review",
          "addComment": "Add Comment",
          "changeAddress": "Change Address",
          "scheduleSendTime": "Scedule Send Time",
          "lessThan8": "Should be none less than 8 characters",
          "welcomeMessage": "Hello set the User name here",
          "introducingMessage":
              "Explore our stunning collection of flowers and vibrant plants to brighten every occasion.",
          "expectedDate": "Expected Date:",
          "expectedTime": "Expected Time:",
          "delivery": "Delivery:",
          "taxes": "Taxes:",
          "totalPrice": "Total Price:",
          "payment": "Payment",
          "townOrCity": "Town/City",
          "addressInstructions": "Special Instructions About Address",
          "location": "Use My Location",
          "debitCard": "Debit Card",
          "creditCard": "Credit Card",
          "paypal": "Pay Pal",
          "digitalWallet": "Digital Wallet",
          "cardInfo": "Card Information",
          "cardHolderName": "Card Holder Full Name",
          "cardNumber": "Card Number",
          "expirationDate": "Expiration Date",
          "futurePurshace": "Save For Future Purchases",
          "name": "Name",
          "arabic": "Arabic",
          "checkInternetConnection": "Please Check Your Internet Connection ",
          'english': "English",
          "logOutFailMessage":
              "Something went wrong while logging out please try again",
          "darkMode": "Dark Mode",
        },
        "ar": {
          "themes": "الثيمات",
          "darkMode": "الوضع المظلم",
          "gallery": "المعرض",
          "camera": "الكاميرا",
          "chooseImage": "اختر صورة",
          "logo": "الشعار",
          "login": "تسجيل الدخول",
          "signUp": "اشتراك",
          "theSignUp": "الاشتراك",
          "continue": "المتابعة",
          "filter": "تصفية",
          "bestSellers": "أفضل المبيعات",
          "mostGifted": "الأكثر اهداء",
          "offers": "العروض",
          "username": "اسم المستخدم",
          "password": "كلمة المرور",
          "repassword": "إعادة كلمة المرور",
          "address": "العنوان: ",
          "email": "البريد",
          "phoneNumber": "رقم الهاتف",
          "forgetPassword": "هل نسيت كلمة المرور؟",
          "noAccount": "ليس لدبك حساب؟",
          "changeAddress": "تغيير العنوان",
          "helloUser": "مرحبا بالمستخدم",
          "customizeSpecialGifts": "اطلب هديتك الخاصة",
          "search": "بحث",
          "gifts": " الهدايا",
          "flowers": "الزهور",
          "plants": "النباتات",
          "bouquet": "بوكي ورد",
          "scheduleSendTime": "تحديد تاريخ الوصول",
          "profilePhoto": "إضافة صورة الملف الشخصي",
          "checkInternetConnection": "حدثت مشكلة تأكد من اتصالك بالانترنت",
          "uploadPdf": "تحميل ملف pdf",
          "hasAccount": "لديك حساب بالفعل",
          "reSendCode": "إعادة إرسال الرمز",
          "verficationCode": "رمز التحقق",
          "enterCodeMessage":
              "الرجاء إدخال رمز التحقق المرسل إلى عنوان البريد الإلكتروني .....@Gmail.com",
          "10minsValid": "صالحة لمدة 10 دقائق",
          "submit": "موافق",
          "plusOne": "+1",
          "price": "السعر: ",
          "addToCart": "إضافة إلى السلة ",
          "color": "اللون",
          "flowerInfo": "معلومات عن الزهرة",
          "takeCareOfPlant": "كيفية الاعتناء بالزهرة",
          "addToBasket": "إضافة إلى سلة المشتريات",
          "buyNow": "اشتري الاّن",
          "reviews": "الاّراء",
          "dateOfReview": "التاريخ",
          "addComment": "إضافة تعليق",
          "done": "موافق",
          "settings": "الاعدادات",
          "accountInformation": "معلومات الحساب",
          "paymentMethod": "وسيلة الدفع",
          "paymentMethods": "وسائل الدفع",
          "orderHistory": "تاريخ الطلبات",
          "securitySettings": "اعدادات الأمان",
          "suuport&feedback": "ردود الفعل و الدعم",
          "languageSettings": "اعدادات اللغة",
          "legalInformation": "المعلومات القانونية",
          "logOut": "تسجيل الخروج",
          "aboutUs": "حول المتجر",
          "logOutmessage": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "yes": "نعم",
          "no": "لا",
          "order": " الطلب: ",
          "tryAgain": "أعد المحاولة",
          "logOutFailMessage":
              "حدث خطأ اثناء محاولة تسجيل الخروج يرجى المحاولة مرة ثانية",
          "ok": "موافق",
          "lessThan8": "يجب أن لا يقل عن 8 محارف",
          "verificationCodeContent": "رمز التحقق يتكون من أرقام و حروف",
          "welcomeMessage": "أهلا بالمستخدم",
          "introducingMessage":
              "استكشف مجموعتنا المذهلة من الزهور و النباتات النابضة بالحياة لاضفاء البهجة على كل مناسبة   ",
          "expectedDate": "تاريخ وصول الطلب:",
          "expectedTime": "الوقت المتوقع لوصول الطلب:",
          "delivery": "كلفةالتوصيل:",
          "taxes": "الضرائب:",
          "totalPrice": "السعر النهائي:",
          "cart": "سلة المشتريات",
          "payment": "الدفع",
          "catOfFlowers": "فئات الزهور",
          "townOrCity": "البلد/المدينة",
          "addressInstructions": "تعليمات خاصة حول العنوان",
          "location": "استخدام الموقع",
          "debitCard": "بطاقة الخصم",
          "creditCard": "بطاقة الائتمان",
          "paypal": "بايبال",
          "digitalWallet": "محفظة رقمية",
          "cardInfo": "معلومات البطاقة",
          "cardHolderName": "الاسم الكامل لحامل البطاقة",
          "cardNumber": "رقم البطاقة",
          "expirationDate": "تاريخ انتهاء الصلاحية",
          "futurePurshace": "حفظ بيانات البطاقة للمشتريات المستقبلية",
          "name": "الاسم",
          "arabic": "العربية",
          'english': "الانكليزية",
          //-------------------errors
        },
      };
}
